# -----------------------------
# Traefik Static Configuration
# -----------------------------
# traefik.yml

# Entrypoints for HTTP and HTTPS
entryPoints:
  web:
    address: ":90"               # Local host HTTP port (mapped from 90:80)
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":8443"             # Local host HTTPS port (mapped from 8443:443)

# Enable Docker provider
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false      # Only containers with label traefik.enable=true are exposed

# Logging
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

# Access logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# Let's Encrypt ACME configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "${TRAEFIK_EMAIL}"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web